=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xsd/bozze.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:boz="http://www.tesina/bozze"
			targetNamespace="http://www.tesina/bozze">

    <xsd:element name="bozze">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="boz:bozza" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="bozza">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="boz:categorie" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="boz:descrizione" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="boz:tutorial_bozza" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" />
			<xsd:attribute name="id_creator" type="xsd:positiveInteger" />
			<xsd:attribute name="tempo_medio" type="xsd:positiveInteger" />
			<xsd:attribute name="file_img" type="xsd:string" />
			<xsd:attribute name="data_pubblicazione" type="xsd:dateTime" />
			<xsd:attribute name="visualizzazioni" type="xsd:positiveInteger" />
			<xsd:attribute name="difficolta" type="boz:tipiDifficolta" />
            <xsd:attribute name="completo" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="categorie">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="boz:categoria" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="categoria">
		<xsd:complexType>
			<xsd:attribute name="id_categoria" type="xsd:ID" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="descrizione" type="xsd:string" />

	<xsd:element name="reports_progetti">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="boz:report_progetto" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="report_progetto">
		<xsd:complexType>
			<xsd:attribute name="id_report" type="xsd:positiveInteger"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="tutorial_bozza">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="boz:step" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="step">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="boz:descrizione" use="required" />
				<xsd:element ref="boz:immagine" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="descrizione" type="xsd:string" />

	<xsd:element name="immagine" type="xsd:base64binary" />

	<xsd:simpleType name="tipoDifficolta">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="facile" />
			<xsd:enumeration value="medio" />
			<xsd:enumeration value="difficile" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/bozze.xml
<?xml version="1.0" encoding="UTF-8"?>
<bozze xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ultimo_id="31" xsi:noNamespaceSchemaLocation="../../structures/xsd/bozze.xsd">
  <bozza sospeso="false" id="28" titolo="ef" id_creator="3" tempo_medio="1" data_pubblicazione="2024-02-03 18:12:37" difficolta="facile" clearance="1" nome_file_img="">
    <categorie>
      <categoria id_categoria="1"/>
    </categorie>
    <categoriaProposta/>
    <descrizione>esf</descrizione>
    <tutorial_bozza>
      <step titolo_step="wrewe" num_step="1" nome_file_img="img/steps/img_step_65be7358de113.webp">
        <descrizione>werwe</descrizione>
      </step>
      <step titolo_step="asd" num_step="3" nome_file_img="img/steps/img_step_65be73488789b.webp">
        <descrizione>asdsd</descrizione>
      </step>
      <step titolo_step="w" num_step="4" nome_file_img="img/steps/img_step_65be6cf8c7767.jpg">
        <descrizione>wd</descrizione>
      </step>
      <step titolo_step="s" num_step="5" nome_file_img="img/steps/img_step_65be6d156760e.jpg">
        <descrizione>s</descrizione>
      </step>
    </tutorial_bozza>
  </bozza>
  <bozza sospeso="false" id="31" titolo="ef" id_creator="3" tempo_medio="1" data_pubblicazione="2024-02-03 18:17:02" difficolta="facile" clearance="1" nome_file_img="">
    <categorie>
      <categoria id_categoria="1"/>
    </categorie>
    <categoriaProposta/>
    <descrizione>esf</descrizione>
    <tutorial_bozza>
      <step titolo_step="es" num_step="1" nome_file_img="img/steps/img_step_65be6ba89b388.jpg">
        <descrizione>s&lt;g</descrizione>
      </step>
      <step titolo_step="asd" nome_file_img="img/steps/img_step_65be751958ad6.webp" num_step="2">
        <descrizione>&gt;</descrizione>
      </step>
    </tutorial_bozza>
  </bozza>
</bozze>
