=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/structures/xsd/categorie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="categorie">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="categoria" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimo_id" type="xsd:integer" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="categoria">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nomeCategoria" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="nomeCategoria" type="xsd:string" />

</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/categorie.xml
<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<categorie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ultimo_id="5" xsi:noNamespaceSchemaLocation="../../structures/xsd/categorie.xsd">
=======
<categorie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ultimo_id="7" xsi:noNamespaceSchemaLocation="../../structures/xsd/categorie.xsd">
>>>>>>> 2f788540b7e4e840b21ebd2c342675ca74163540
  <categoria id="1">
    <nomeCategoria>Informatica</nomeCategoria>
  </categoria>
  <categoria id="2">
    <nomeCategoria>Elettronica</nomeCategoria>
  </categoria>
  <categoria id="3">
    <nomeCategoria>Robotica</nomeCategoria>
  </categoria>
  <categoria id="4">
    <nomeCategoria>Domotica</nomeCategoria>
  </categoria>
  <categoria id="5">
    <nomeCategoria>Riciclo Creativo</nomeCategoria>
  </categoria>
  <categoria id="7">
    <nomeCategoria>Supermacchine</nomeCategoria>
  </categoria>
</categorie>
