=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/structures/xsd/commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:com="http://www.tesina/commenti"
			targetNamespace="http://www.tesina/commenti">

	<xsd:element name="commenti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="com:commento" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="commento">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="com:testo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="com:voto" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="com:reports_commento" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" />
			<xsd:attribute name="id_commentatore" type="xsd:positiveInteger" />
			<xsd:attribute name="id_discussione" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element> 

	<xsd:element name="testo" type="xsd:string" />

	<xsd:element name="voto">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="com:utilita" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="com:livello_di_accordo" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id_votante" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="utilita" type="com:tipoUtilita" />

	<xsd:simpleType name="tipoUtilita">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="5" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="livello_di_accordo" type="com:tipoAccordo" />

	<xsd:simpleType name="tipoAccordo">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="3" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="reports_commento">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="com:report_commento" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="report_commento">
		<xsd:complexType>
			<xsd:attribute name="id_report" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/commenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<commenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../structures/commenti.xsd">
  <commento id="1" id_discussione="1" id_commentatore="3" data_ora="2023-11-24 11:08:57">
    <testo>commentoooo</testo>
    <voti/>
    <reports_commento>
      <report_commento id_report="1"/>
    </reports_commento>
  </commento>
  <commento id="2" id_discussione="2" id_commentatore="3" data_ora="2023-11-24 11:09:19">
    <testo>wAFESR</testo>
    <voti/>
    <reports_commento/>
  </commento>
</commenti>
