=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/structures/xsd/discussioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:disc="http://www.tesina/discussioni"
			targetNamespace="http://www.tesina/discussioni">

	<xsd:element name="discussioni">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="discussione" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimo_id" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="discussione">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="disc:commenti" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="disc:descrizione" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="disc:partecipanti" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="titolo" type="xsd:string" />
			<xsd:attribute name="id_poster" type="xsd:positiveInteger" />
			<xsd:attribute name="id" type="xsd:positiveInteger" />
			<xsd:attribute name="risolta" type="xsd:boolean" />
			<xsd:attribute name="id_progetto" type="xsd:positiveInteger" />
			<xsd:attribute name="data_ora" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="commenti">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="disc:commento" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="commento">
		<xsd:complexType>
			<xsd:attribute name="id_commento" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="partecipanti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="disc:partecipante" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="partecipante">
		<xsd:complexType>
			<xsd:attribute name="id_partecipante" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="descrizione" type="xsd:string" />

</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/discussioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<discussioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ultimo_id="7" xsi:noNamespaceSchemaLocation="../../structures/discussioni.xsd">
  <discussione titolo="titolo 13" id_poster="1" risolta="false" id="6" id_progetto="13" data_ora="2023-12-01 14:51:28">
    <commenti>
      <commento id_commento="13"/>
    </commenti>
    <descrizione>descr</descrizione>
    <partecipanti>
      <partecipante id_partecipante="7"/>
    </partecipanti>
  </discussione>
  <discussione titolo="wergf" id_poster="" risolta="false" id="7" id_progetto="13" data_ora="2023-12-04 18:12:47">
    <commenti>
      <commento id_commento="15"/>
    </commenti>
    <descrizione>w</descrizione>
    <partecipanti>
      <partecipante id_partecipante="7"/>
    </partecipanti>
  </discussione>
</discussioni>
