=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/structures/xsd/storici.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="storici">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="storico" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="ultimo_id" type="xsd:integer" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="storico">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="progetti" minOccurs="1" maxOccurs="1" /> 
                <xsd:element ref="richieste" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="commenti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="valutazioni_progetti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="reports_progetti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="reports_commenti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="discussioni" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="valutazioni_commenti" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id_utente" type="xsd:positiveInteger" />
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="progetti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="progetto" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="progetto">
        <xsd:complexType>
            <xsd:attribute name="id_progetto" type="xsd:positiveInteger" />
            <xsd:attribute name="titolo" type="xsd:string" /> 
            <xsd:attribute name="data_ora" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="richieste">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="richiesta" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="richiesta">
        <xsd:complexType>
            <xsd:attribute name="id_richiesta" type="xsd:positiveInteger" /> 
            <xsd:attribute name="id_discussione" type="xsd:positiveInteger" /> 
            <xsd:attribute name="data_ora" type="xsd:string" />
            <xsd:attribute name="titolo" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="commenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="commento" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="commento">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="testo" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id_commento" type="xsd:positiveInteger" />
            <xsd:attribute name="id_discussione" type="xsd:positiveInteger" />
            <xsd:attribute name="data_ora" type="xsd:string" /> 
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="testo" type="xsd:string" />

    <xsd:element name="valutazioni_progetti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="valutazione_progetto" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="valutazione_progetto">
        <xsd:complexType>
            <xsd:attribute name="id_valutazione" type="xsd:positiveInteger" />
            <xsd:attribute name="data_ora" type="xsd:string" />  
            <xsd:attribute name="id_progetto" type="xsd:positiveInteger" />
            <xsd:attribute name="value" type="xsd:positiveInteger" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="reports_progetti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="report_progetto" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="report_progetto">
        <xsd:complexType>
            <xsd:attribute name="id_report" type="xsd:positiveInteger" /> 
            <xsd:attribute name="id_progetto" type="xsd:positiveInteger" />  
            <xsd:attribute name="data_ora" type="xsd:string" />
            <xsd:attribute name="tipo" type="xsd:string" /> 
            <xsd:attribute name="publisher" type="xsd:string" /> 
            <xsd:attribute name="titolo" type="xsd:string" /> 
        </xsd:complexType>
    </xsd:element>

        <xsd:element name="reports_commenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="report_commento" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="report_commento">
        <xsd:complexType>
            <xsd:attribute name="id_report" type="xsd:positiveInteger" />
            <xsd:attribute name="id_commento" type="xsd:positiveInteger" />  
            <xsd:attribute name="data_ora" type="xsd:string" />
            <xsd:attribute name="tipo" type="xsd:string" /> 
            <xsd:attribute name="commentatore" type="xsd:string" /> 
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="discussioni">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="discussione" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="discussione">
        <xsd:complexType>
            <xsd:attribute name="id_discussione" type="xsd:positiveInteger" />
            <xsd:attribute name="data_ora" type="xsd:string" />
            <xsd:attribute name="titolo" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="valutazioni_commenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="valutazione_commento" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="valutazione_commento">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="1">
                <xsd:element ref="utilita" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="livello_di_accordo" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="id_valutazione" type="xsd:positiveInteger" /> 
            <xsd:attribute name="data_ora" type="xsd:string" />  
            <xsd:attribute name="id_progetto" type="xsd:positiveInteger" />
            <xsd:attribute name="id_commento" type="xsd:positiveInteger" />
        </xsd:complexType>
    </xsd:element> 

    <xsd:element name="utilita" type="tipoUtilita" />

    <xsd:simpleType name="tipoUtilita">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="5" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="livello_di_accordo" type="tipoAccordo" />

    <xsd:simpleType name="tipoAccordo">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1" />
            <xsd:maxInclusive value="3" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/storici.xml
<?xml version="1.0" encoding="UTF-8"?>
<storici xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ultimo_id="0" xsi:noNamespaceSchemaLocation="../../structures/storici.xsd">
  <storico id_utente="6">
    <progetti>
      <progetto titolo="titolo" id_progetto="5"/>
      <progetto titolo="titolo" id_progetto="6"/>
      <progetto titolo="rg" id_progetto="7"/>
    </progetti>
    <richieste/>
    <commenti>
      <commento id_commento="1">
        <testo>q3wf</testo>
      </commento>
      <commento id_commento="2">
        <testo>waEGR</testo>
      </commento>
      <commento id_commento="3">
        <testo>QWERF</testo>
      </commento>
      <commento id_commento="4">
        <testo>ARH</testo>
      </commento>
      <commento id_commento="5">
        <testo>r3f</testo>
      </commento>
      <commento id_commento="6">
        <testo>warg</testo>
      </commento>
      <commento id_commento="7">
        <testo>AEF</testo>
      </commento>
      <commento id_commento="8">
        <testo>agwe</testo>
      </commento>
      <commento id_commento="9">
        <testo>ew5yh</testo>
      </commento>
      <commento id_commento="10">
        <testo>eh5</testo>
      </commento>
      <commento id_commento="11">
        <testo>w3r</testo>
      </commento>
      <commento id_commento="12">
        <testo>4qwt</testo>
      </commento>
    </commenti>
    <valutazioni_progetti/>
    <reports_progetti/>
    <reports_commenti/>
    <discussioni>
      <discussione id_discussione="2" titolo="tits prog 5"/>
      <discussione id_discussione="3" titolo="tits prog 5"/>
      <discussione id_discussione="4" titolo="23"/>
      <discussione id_discussione="5" titolo="QWd"/>
    </discussioni>
    <valutazioni_commenti/>
  </storico>
</storici>
