=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/structures/xsd/tutorials_progetti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="tutorials_progetti">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tutorial_progetto" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="ultimo_id" type="xsd:integer" />
		</xsd:complexType>
	</xsd:element>

    <xsd:element name="tutorial_progetto">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="step" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:positiveInteger" />
            <xsd:attribute name="id_progetto" type="xsd:positiveInteger" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="step">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="descrizione" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="titolo_step" type="xsd:string" />
			<xsd:attribute name="num_step" type="xsd:positiveInteger" />
			<xsd:attribute name="nome_file_img" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="descrizione" type="xsd:string" />

</xsd:schema>

=== spagnolivalerio/lweb-homework-2022-2023/4-TESINA/data/xml/tutorials.xml
<?xml version="1.0" encoding="UTF-8"?>
<tutorials_progetti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../structures/tutorials_progetti.xsd" ultimo_id="1">
  <tutorial_progetto id="1" id_progetto="1">
    <step num_step="1" nome_file_img="img/steps/img_step_659bd05245a40.jpg">
      <descrizione>Collegare arduino al pc con un cavo usb tipo B - tipo A.</descrizione>
    </step>
    <step num_step="2" nome_file_img="img/steps/img_step_659bd097b7901.png">
      <descrizione>Aprire l'ide di programmazione arduino e caricare lo sketch di default chiamato "blink"</descrizione>
    </step>
    <step num_step="3" nome_file_img="img/steps/img_step_659bd141ef448.jpg">
      <descrizione>Collegare con i jump, il pin 9 analogico di arduino sull'anodo del led, e la massa sul catodo. Infine avviare lo sketch caricandolo su arduino.</descrizione>
    </step>
  </tutorial_progetto>
</tutorials_progetti>
